version: '3'
services:
  sdnext:
    image: saladtechnologies/sdnext:dynamic
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7860:7860
    environment:
      # A comma separated list of model version ids to load
      CIVITAI_MODEL_VERSION_IDS: 131579

      # Set to 1 to enable the refiner
      LOAD_REFINER: 0
