#! /usr/bin/env bash

## Usage: ./build [--push] [--civitai-version-ids 122143,128713] [--load-refiner] [--load-sdxl-base] [--tag tag]

set -euo pipefail

# parse args
push=false
load_refiner=0
load_sdxl_base=0
civitai_model_version_ids=""
tag=""
while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
  --push)
    push=true
    shift
    ;;
  --load-refiner)
    load_refiner=1
    shift
    ;;
  --load-sdxl-base)
    load_sdxl_base=1
    shift
    ;;
  --civitai-version-ids)
    civitai_model_version_ids="$2"
    shift
    shift
    ;;
  --tag)
    tag="$2"
    shift
    shift
    ;;
  *)
    echo "Unknown option $key"
    exit 1
    ;;
  esac
done

git_sha=$(git rev-parse --short HEAD)

# the default tag is the version ids with a hypen between them
if [[ -z $tag ]]; then
  tag=$(echo $civitai_model_version_ids | tr ',' '-')
fi
base_tag="dynamic"

docker buildx build \
  -t saladtechnologies/sdnext:$tag \
  -f Dockerfile.baked \
  --platform linux/amd64 \
  --output type=docker \
  --provenance false \
  --build-arg VERSION=$base_tag \
  --build-arg CIVITAI_MODEL_VERSION_IDS=$civitai_model_version_ids \
  --build-arg LOAD_REFINER=$load_refiner \
  --build-arg LOAD_SDXL_BASE=$load_sdxl_base \
  .

docker tag saladtechnologies/sdnext:$tag saladtechnologies/sdnext:$tag-$git_sha

if [[ $push == true ]]; then
  echo "Pushing saladtechnologies/sdnext:$tag"
  docker push saladtechnologies/sdnext:$tag

  echo "Pushing saladtechnologies/sdnext:$tag-$git_sha"
  docker push saladtechnologies/sdnext:$tag-$git_sha
fi
